version: '3'

services:
  rstudio:
    build: .
    image: geo:geospatial
    container_name: geo
    ports:
      - 8787:8787
    environment:
      PASSWORD: YOUR_PASS
    volumes:
      - ./:/home/rstudio
    tty: true
    stdin_open: true
